import { Maximize2, Play, EyeOff, Shuffle, Wand } from 'lucide-react';
  
  export const CARDS = {
    GIANT_MODE: {
      id: 'giant',
      name: 'Giant Mode',
      description: 'Place any disk anywhere',
      icon: Maximize2,
      rarity: 'rare',
      duration: 1,
      color: 'bg-purple-500/30',
      activeColor: 'rgba(147, 51, 234, 0.5)',
      effectClass: 'effect-giant',
      isNegative: false,
      weight: 40,
      type: 'loadable'
    },
    TIME_WARP: {
      id: 'timewarp',
      name: 'Time Warp',
      description: '3 free moves <3',
      icon: Play,
      rarity: 'rare',
      duration: 1,
      color: 'bg-blue-500/30',
      activeColor: 'rgba(59, 130, 246, 0.5)',
      effectClass: 'effect-timewarp',
      isNegative: false,
      weight: 30,
      type: 'loadable'
    },
    DOUBLE_MOVE: {
      id: 'double',
      name: 'Double Move',
      description: '( ͡° ͜ʖ ͡°)',
      icon: Play,
      rarity: 'common',
      duration: 1,
      color: 'bg-blue-500/30',
      activeColor: 'rgba(59, 130, 246, 0.5)',
      effectClass: 'effect-double',
      isNegative: false,
      weight: 50,
      type: 'loadable'
    },
    COLOR_INVERT: {
      id: 'invert',
      name: 'Color Blast',
      description: 'Behold! Razzle Dazzle!',
      icon: Play,
      rarity: 'common',
      duration: 3,
      color: 'bg-orange-500/30',
      activeColor: 'rgba(249, 115, 22, 0.5)',
      effectClass: 'effect-invert',
      isNegative: true,
      weight: 50,
      type: 'auto'
    },
    SCRAMBLE: {
      id: 'scramble',
      name: 'Scramble',
      description: 'Redistribute all disks once',
      icon: Shuffle,
      rarity: 'rare',
      duration: 1,
      color: 'bg-red-500/30',
      activeColor: 'rgba(239, 68, 68, 0.5)',
      effectClass: 'effect-scramble',
      isNegative: false,
      weight: 30,
      type: 'instant'
    },
    TOWER_LOCK: {
      id: 'lock',
      name: 'Tower Lock',
      description: 'Random tower locks for 1 move',
      icon: Play,
      rarity: 'common',
      duration: 1,
      color: 'bg-yellow-500/30',
      activeColor: 'rgba(234, 179, 8, 0.5)',
      effectClass: 'effect-lock',
      isNegative: true,
      weight: 40,
      type: 'auto'
    },
    TOWER_SWAP: {
      id: 'towerswap',
      name: 'Tower Swap',
      description: 'Randomly swaps two towers',
      icon: Shuffle,
      rarity: 'rare',
      duration: 1,
      color: 'bg-red-500/30',
      activeColor: 'rgba(239, 68, 68, 0.5)',
      effectClass: 'effect-towerswap',
      isNegative: true,
      weight: 50,
      type: 'instant'
    },
    BLIND_MOVE: {
      id: 'blind',
      name: 'Blind Move',
      description: 'Memorize the board and play blind',
      icon: EyeOff,
      rarity: 'common',
      duration: 1,
      color: 'bg-yellow-500/30',
      activeColor: 'rgba(234, 179, 8, 0.5)',
      effectClass: 'effect-blind',
      isNegative: true,
      weight: 30,
      type: 'auto'
    },
    WILD_CARD: {
      id: 'wildcard',
      name: 'Wild Card',
      description: 'Remove next card from deck',
      icon: Wand,
      rarity: 'rare',
      duration: 1,
      color: 'bg-indigo-500/50',
      activeColor: 'rgba(99, 102, 241, 0.5)',
      effectClass: 'effect-wildcard',
      isNegative: false,
      weight: 40,
      type: 'special'
    }
  };